### ISSUE TITLE
CLI Error(Seems like the code is not working with latest node)

### ISSUE THREAD

**Issue by coleander** [mmckegg/msi-packager#7]
Running the cli to generate and msi package, i recieve: 

```
(node:26611) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
/usr/lib/node_modules/msi-packager/cli.js:73
  if (err) throw err
           ^

Error: spawn wixl ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by salvatoretrimarchi** [comment]
You need to install wixl
apt-get install wixl
